import type {
  DebugAdapterProvider,
  ExecutionEnvironmentProvider,
  ExecutionProfileContributionProvider,
  InteractiveSessionHookProvider,
  InteractiveSessionProvider,
  LanguageProvider,
  PluginExtensionApi,
  PluginSettingsProvider,
  ResourceContextMenuProvider,
  ResourceDecorationProvider,
  ResourceIconProvider,
  ScriptExecutionContribution,
  TextEditorContextMenuProvider,
  TextEditorLineDecorationProvider,
  TextEditorNavigationProvider,
  WorkbenchEditorToolbarProvider,
  WorkbenchExecutionViewProvider,
  WorkbenchExplorerFilterProvider,
  WorkbenchExplorerIgnoreProvider,
  WorkbenchFontProvider,
  WorkbenchHtmlPreviewProvider,
  WorkbenchIconProvider,
  WorkbenchPanelHook,
  WorkbenchResourceEditorProvider,
  WorkbenchSidebarHook,
  WorkbenchStatusbarContribution,
  WorkbenchThemeProvider,
  WorkbenchTitlebarContribution,
  WorkbenchToolWindowHook,
  WorkspaceFileCreationProvider,
} from "@tinyide/plugin-api";
import type { TinyIdePlatform } from "./platform";

export function createExtensionApi(platform: TinyIdePlatform): PluginExtensionApi {
  return {
    registerLanguageProvider: (provider: LanguageProvider) => platform.capabilities.register("language.provider", provider),
    registerResourceIconProvider: (provider: ResourceIconProvider) => platform.capabilities.register("resource.icon", provider),
    registerResourceDecorationProvider: (provider: ResourceDecorationProvider) => platform.capabilities.register("resource.decoration", provider),
    registerWorkspaceFileCreationProvider: (provider: WorkspaceFileCreationProvider) => platform.capabilities.register("workspace.fileCreation", provider),
    registerExecutionEnvironmentProvider: (provider: ExecutionEnvironmentProvider) => platform.capabilities.register("execution.environment", provider),
    registerExecutionProfileContributionProvider: (provider: ExecutionProfileContributionProvider) => platform.capabilities.register("execution.profile.contribution", provider),
    registerDebugAdapterProvider: (provider: DebugAdapterProvider) => platform.capabilities.register("execution.debugAdapter", provider),
    registerScriptExecution: (contribution: ScriptExecutionContribution) => platform.capabilities.register("execution.script", contribution),
    registerResourceContextMenuProvider: (provider: ResourceContextMenuProvider) => platform.capabilities.register("resource.contextMenu", provider),
    registerTextEditorContextMenuProvider: (provider: TextEditorContextMenuProvider) => platform.capabilities.register("textEditor.contextMenu", provider),
    registerTextEditorNavigationProvider: (provider: TextEditorNavigationProvider) => platform.capabilities.register("textEditor.navigation", provider),
    registerInteractiveSessionHook: (provider: InteractiveSessionHookProvider) => platform.capabilities.register("interactive.session.hook", provider),
    registerInteractiveSessionProvider: (provider: InteractiveSessionProvider) => platform.capabilities.register("interactive.session", provider),
    getInteractiveSessionHooks: () => platform.capabilities.getAll<InteractiveSessionHookProvider>("interactive.session.hook"),
    registerPluginSettingsProvider: (provider: PluginSettingsProvider) => platform.capabilities.register("plugin.settings", provider),
    registerWorkbenchSidebarHook: (hook: WorkbenchSidebarHook) => platform.capabilities.register("workbench.sidebar.hook", hook),
    registerWorkbenchPanelHook: (hook: WorkbenchPanelHook) => platform.capabilities.register("workbench.panel.hook", hook),
    registerWorkbenchToolWindowHook: (hook: WorkbenchToolWindowHook) => platform.capabilities.register("workbench.toolWindow.hook", hook),
    registerWorkbenchThemeProvider: (provider: WorkbenchThemeProvider) => platform.capabilities.register("workbench.theme", provider),
    registerWorkbenchFontProvider: (provider: WorkbenchFontProvider) => platform.capabilities.register("workbench.font", provider),
    registerWorkbenchIconProvider: (provider: WorkbenchIconProvider) => platform.capabilities.register("workbench.icon", provider),
    registerWorkbenchTitlebarContribution: (contribution: WorkbenchTitlebarContribution) => platform.capabilities.register("workbench.titlebar", contribution),
    registerWorkbenchStatusbarContribution: (contribution: WorkbenchStatusbarContribution) => platform.capabilities.register("workbench.statusbar", contribution),
    registerWorkbenchExplorerFilterProvider: (provider: WorkbenchExplorerFilterProvider) => platform.capabilities.register("workbench.explorerFilter", provider),
    registerWorkbenchExplorerIgnoreProvider: (provider: WorkbenchExplorerIgnoreProvider) => platform.capabilities.register("workbench.explorerIgnore", provider),
    registerWorkbenchEditorToolbarProvider: (provider: WorkbenchEditorToolbarProvider) => platform.capabilities.register("workbench.editorToolbar", provider),
    registerTextEditorLineDecorationProvider: (provider: TextEditorLineDecorationProvider) => platform.capabilities.register("textEditor.lineDecoration", provider),
    registerWorkbenchResourceEditorProvider: (provider: WorkbenchResourceEditorProvider) => platform.capabilities.register("workbench.resourceEditor", provider),
    registerWorkbenchHtmlPreviewProvider: (provider: WorkbenchHtmlPreviewProvider) => platform.capabilities.register("workbench.htmlPreview", provider),
    getWorkbenchHtmlPreviewProviders: () => platform.capabilities.getAll<WorkbenchHtmlPreviewProvider>("workbench.htmlPreview"),
    registerWorkbenchExecutionViewProvider: (provider: WorkbenchExecutionViewProvider) => platform.capabilities.register("workbench.executionView", provider),
  };
}
